Feature/mq1 profile layout
Mirian97/portfolio pull request #1
Opened 2023-05-31 11:46 UTC by Mirian97

2023-05-31 17:04 UTC, alefsilva requested changes

2023-05-31 17:04 UTC, alefsilva commented on src/constants/skills.ts
> +    iconSource: 'https://skillicons.dev/icons?i=html'
Como a url https://skillicons.dev/icons?i= é igual para todos os ícones, poderia ficar em uma constante acima.

2023-05-31 17:04 UTC, alefsilva commented on src/app/Profile.tsx
> +        height={197}
Nas imagens. não tem necessidade de especificar o height. Por padrão é automático e já fica proporcional com a largura.

2023-05-31 17:04 UTC, alefsilva commented on public/svg/avatar.svg
Quando há bordas ou sombras nas imagens, o ideal é criar esses estilos através do CSS para ficar melhor a renderização na tela.

2023-05-31 17:30 UTC, Mirian97 commented on public/svg/avatar.svg
Entendi, poderia disponibilizar a imagem, no figma só consigo importar as bordas e as sombras prontas

2023-05-31 17:31 UTC, Mirian97 commented on src/app/Profile.tsx
> +        height={197}
É que no Next, width e height se tornam obrigatórios em Image, mas posso ver um jeito de deixar sem.

2023-06-01 00:43 UTC, alefsilva commented on public/svg/avatar.svg
![mirian_quispe_desenvolvedora_full_stack](https://github.com/Mirian97/portfolio/assets/36169624/55c2fb4b-b138-41eb-9a73-66ea4e94a966)

2023-06-01 00:49 UTC, alefsilva approved these changes

2023-06-01 00:49 UTC, merged