Feature/mq10 send form
Mirian97/portfolio pull request #12
Opened 2023-06-08 12:03 UTC by Mirian97

2023-06-08 13:30 UTC, alefsilva requested changes

2023-06-08 13:30 UTC, alefsilva commented on src/app/contact/Modal.tsx
> +  closeModal: () => void
No lugar de colocar um arrow funciton na inteface, para métodos, pode por simplesmente **Function**

2023-06-08 13:30 UTC, alefsilva commented on src/app/contact/Modal.tsx
> +    return () => toggleBodyScroll(false)
No lugar dessa condicional e de outro return, pode pode simplicar com:
`toggleBodyScroll(openModal)`

2023-06-08 13:30 UTC, alefsilva commented on src/constants/emailjs.ts
> +  serviceId: 'service_5ji5v6f',
O correto são esses dados ficaram em variáveis de ambiente.

2023-06-08 13:30 UTC, alefsilva commented on src/app/contact/page.tsx
> +          errorMessage={errors.from_name?.message}
Aqui nesse errorMessage está dando erro de typescript, uma forma de resolver é criando um método intermediário para verificar o schema que fez com o yup como no código abaixo:
```
const renderContactForm = () => {
    const checkSchemaType = (value: contactSchemaType) =>
      typeof value === 'string' ? value : ''
    return (
      <form onSubmit={handleSubmit(onSubmit)} className='mt-8 grid grid-cols-1 gap-4'>
        <div className='flex flex-col gap-4 sm:flex-row'>
          <Input
            label='Nome *'
            placeholder='Exe.: João Aparecido'
            {...register('from_name')}
            error={Boolean(errors.from_name)}
            errorMessage={checkSchemaType(errors?.from_name?.message)}
          />
          <Input
            label='Assunto'
            placeholder='Exe.: Orçamento'
            {...register('subject')}
            error={Boolean(errors.subject)}
            errorMessage={checkSchemaType(errors.subject?.message)}
          />
        </div>
        <Input
          label='E-mail *'
          placeholder='joao.aparecido@gmail.com'
          startIcon={<EmailIcon width={20} />}
          {...register('email')}
          error={Boolean(errors.email)}
          errorMessage={checkSchemaType(errors.email?.message)}
        />
        <TextArea
          label='Mensagem *'
          placeholder='Diga como posso te ajudar...'
          {...register('message')}
          error={Boolean(errors.message)}
          errorMessage={checkSchemaType(errors.message?.message)}
          maxLength={400}
          value={messageValue}
          onChange={(e) => setValue('message', e.target.value)}
        />
        <Button type='submit' size='small' className='w-full sm:w-[150px] ml-auto'>
          Enviar
        </Button>
      </form>
    )
```

2023-06-08 13:30 UTC, alefsilva commented on src/schemas/contactSchema.ts
No import do yup está dando erro. Quando é assim, é porque falta instalar as interfaces da biblioteca com _@types/nome_biblioteca_:

  **npm install @types/yup --save**

2023-06-08 21:32 UTC, Mirian97 commented on src/app/contact/Modal.tsx
> +  closeModal: () => void
Troquei por Function, porém deu erro: Type 'Function' is not assignable to type 'MouseEventHandler<HTMLButtonElement>'.
  Type 'Function' provides no match for the signature '(event: MouseEvent<HTMLButtonElement, MouseEvent>): void'.ts(2322)

2023-06-08 22:54 UTC, Mirian97 commented on src/app/contact/Modal.tsx
> +    return () => toggleBodyScroll(false)
NEXT_PUBLIC_SERVICE_ID='service_5ji5v6f'
NEXT_PUBLIC_TEMPLATE_ID='template_7zxwd2f'
NEXT_PUBLIC_API_KEY='q1BnU3ikmvGhaKn7v'

2023-06-08 22:55 UTC, Mirian97 commented on src/constants/emailjs.ts
> +  serviceId: 'service_5ji5v6f',
NEXT_PUBLIC_SERVICE_ID='service_5ji5v6f'
NEXT_PUBLIC_TEMPLATE_ID='template_7zxwd2f'
NEXT_PUBLIC_API_KEY='q1BnU3ikmvGhaKn7v'

2023-06-08 22:56 UTC, Mirian97 commented on src/app/contact/page.tsx
> +          errorMessage={errors.from_name?.message}
✅

2023-06-09 13:39 UTC, alefsilva commented
Está com conflito

2023-06-09 20:07 UTC, alefsilva approved these changes

2023-06-09 20:07 UTC, merged