Feature/mq12 fix menu
Mirian97/portfolio pull request #13
Opened 2023-06-08 14:05 UTC by Mirian97

2023-06-08 18:48 UTC, alefsilva requested changes

2023-06-08 18:48 UTC, alefsilva commented on src/app/contato/Input.tsx
Embora os nomes das rotas estejam em português, porque se trata do conteúdo para o usuário, se mantém a padronização do nome das pastas e arquivos em inglês como restante do projeto.

2023-06-08 21:25 UTC, Mirian97 commented on src/app/contato/Input.tsx
se eu trocar os nomes das pastas em ingles o next so iria reconhecer pelo nome em inglês e por isso fiz a troca para o português.

2023-06-09 13:38 UTC, alefsilva approved these changes

2023-06-09 13:38 UTC, merged